author: {{cookiecutter.author}}
module: {{cookiecutter.module_name}}
output: docs
theme: fullwidth
xcodebuild_arguments: [-project, '{{cookiecutter.module_name}}.xcodeproj', -scheme, '{{cookiecutter.module_name}}']